# Generated by Django 3.1.7 on 2022-07-02 05:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0002_auto_20220702_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='id',
        ),
        migrations.AddField(
            model_name='produtos',
            name='id_produto',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='codigo',
            field=models.IntegerField(auto_created=True),
        ),
    ]
