# Generated by Django 4.0.5 on 2022-07-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0004_rename_data_alteracao_produtos_data alteração_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='TOTAL',
        ),
    ]
