# Generated by Django 4.0.5 on 2022-07-03 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0005_remove_produtos_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='CÓDIGO',
            new_name='CODIGO',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='DESCRIÇÃO',
            new_name='DESCRICAO',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='USUÁRIO ALTERAÇÃO',
            new_name='USUARIO_ALTERAÇAO',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='USUÁRIO INCLUSÃO',
            new_name='USUARIO_INCLUSAO',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='DATA ALTERAÇÃO',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='DATA INCLUSÃO',
        ),
        migrations.AddField(
            model_name='produtos',
            name='DATA_ALTERAÇAO',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='produtos',
            name='DATA_INCLUSAO',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
