# Generated by Django 3.1.7 on 2022-07-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='id_produto',
            new_name='id',
        ),
    ]
