# Generated by Django 4.0.5 on 2022-07-25 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_alteracao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 25, 10, 35, 38, 767377), null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_inclusao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 25, 10, 35, 38, 767377), null=True),
        ),
    ]
