# Generated by Django 4.0.5 on 2022-07-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0003_auto_20220702_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='data_alteracao',
            new_name='DATA ALTERAÇÃO',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='data_inclusao',
            new_name='DATA INCLUSÃO',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='id_produto',
            new_name='ID_PRODUTO',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='total',
            new_name='TOTAL',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='descricao',
            new_name='USUÁRIO ALTERAÇÃO',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='usuario_alteracao',
            new_name='USUÁRIO INCLUSÃO',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='valor_unit',
            new_name='VALOR',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='usuario_inclusao',
        ),
        migrations.AddField(
            model_name='produtos',
            name='CÓDIGO',
            field=models.CharField(auto_created=True, default='exit', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='DESCRIÇÃO',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
