# Generated by Django 4.0.5 on 2022-07-25 13:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cnpjcpf', models.CharField(blank=True, max_length=14, null=True)),
                ('data_inclusao', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 25, 10, 35, 38, 771376), null=True)),
                ('usuario_inclusao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_alteracao', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 25, 10, 35, 38, 771376), null=True)),
                ('usuario_alteracao', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('rede_social', models.CharField(blank=True, max_length=100, null=True)),
                ('id_licenca', models.ForeignKey(db_column='id_licenca', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_app.licenca')),
            ],
            options={
                'db_table': 'cad_pessoa',
                'managed': True,
            },
        ),
    ]
