# Generated by Django 4.0.5 on 2022-07-25 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id_licenca', models.BigIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('dominio', models.CharField(blank=True, max_length=2000, null=True)),
                ('tenant', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('ativo', models.CharField(default='S', max_length=1)),
            ],
            options={
                'db_table': 'sis_licenca',
                'managed': False,
            },
        ),
    ]
